import {APP_IMAGES} from 'src/assets/images';
import {Routes} from 'src/navigation/route';

export default {
  press_again: 'Press again to Exit App.',
  splash: {
    health_care: 'Healthcare',
    medical_app: 'Medical app',
  },
  intro: {
    intro_title_1: 'Find a lot of specialist doctors in one place',
    intro_title_2: 'Get advice only from a doctor you believe in.',
    skip: 'Skip',
  },
  welcome: {
    title: 'Let’s get started!',
    info: 'Login to Stay healthy and fit ',
    login: 'Login',
    sign_up: 'Sign Up',
  },
  register: {
    ph_name: 'Enter your name',
    ph_email: 'Enter your email',
    ph_password: 'Enter your password',
    agree: 'I agree to the healthcare',
    tnc: ' Terms of Service ',
    policy: 'Privacy Policy',
    do_not_have_acc: 'Don’t have an account?  ',
    sign_in: 'Sign In',
    bl_name: 'Please enter name',
    vl_agree: 'Please agree Terms of services',
  },
  login: {
    sign_in: 'Sign In',
    forgot_password: 'Forgot password?',
    or: 'OR',
    google: 'Sign in with Google',
    facebook: 'Sign in with Facebook',
    vl_email: 'Please enter valid email address',
    vl_pass:
      'Password length must be greater than 6 characters and less than 15 characters',
    bl_email: 'Please enter email',
    bl_pass: 'Please enter password',
  },
  home: {
    welcome: 'welcome !',
    how_going: 'How is it going today ?',
    top_doctors: 'Top Doctors',
    pharmacy: 'Pharmacy',
    ambulance: 'Ambulance',
    health_article: 'Health article',
    see_all: 'See all',
  },
  top_doctor: {
    top_doctors: 'Top Doctors',
    doctor_detail: 'Doctor Detail',
    about: 'About',
    book_apointment: 'Book Apointment',
  },
  pharmacy: {
    Pharmacy: 'Pharmacy',
    upload_prescription: 'Upload Prescription',
    info: 'Order quickly with Prescription',
    popular_product: 'Popular Product',
    product_on_sale: 'Product on Sale',
    description: 'Description',
    buy: 'Buy',
  },
  profile: {
    heart_rate: 'Heart rate',
    calories: 'Calories',
    weight: 'Weight',
  },
  reports: {
    heart_rate: 'Heart rate',
    weight: 'Weight',
    blood_group: 'Blood Group',
    latest_report: 'Latest report',
    general_report: 'General report',
  },
  cart: {
    my_cart: 'My cart',
    payment_detail: 'Payment Detail',
    subtotal: 'Subtotal',
    taxes: 'Taxes',
    total: 'Total',
    payment_method: 'Payment Method',
    change: 'Change',
    checkout: 'Checkout',
  },
  payment: {
    title: 'Payment Success',
    info: 'Your payment has been successful, you can have a consultation session with your trusted doctor',
    btn: 'Back to Home',
  },
  bottom_tab: [
    {
      id: 1,
      icon: APP_IMAGES.ic_home,
      checked_icon: APP_IMAGES.ic_check_home,
      route: Routes.Home,
      title: 'Home',
    },
    {
      id: 2,
      icon: APP_IMAGES.ic_report,
      checked_icon: APP_IMAGES.ic_check_report,
      route: Routes.Reports,
      title: 'Reports',
    },
    {
      id: 3,
      icon: APP_IMAGES.ic_notification,
      checked_icon: APP_IMAGES.ic_check_notification,
      route: Routes.Notification,
      title: 'Notification',
    },
    {
      id: 4,
      icon: APP_IMAGES.ic_profile,
      checked_icon: APP_IMAGES.ic_check_profile,
      route: Routes.Profile,
      title: 'Profile',
    },
  ],
};
